#!/usr/bin/python2

# Show test station status, pull data from server and update page

import traceback, re, cgi, sys, psycopg2, os, base64, datetime

from util import escape, select, table, click, html, authenticate

try:
    
    content="""
    <table id=list></table>

    <script>
    function update(url)
    {
        let response = await fetch(url);
        if (response.ok)
        {
            let data=await response.json();
            s="<tbody>";
            for (r=0; r<data.length; r++)
            {
                s+="<tr>";
                for (d=0; d<data[r].length; d++)
                {
                    s+="<td>" + data[r][d] + "</td>";
                }
                s+="</tr>";
            }
            s+="</tbody>";
            document.getElementById(id).innerHTML = s;
        }
        setTimeout(update,2000);
    }        
    window.onload=update
    </script>
    """
    # print generated content
    print html("Build Manager", 
               "table.data tr:nth-child(even) { background: #CCC; }", 
               content)

except Exception as e:
    print "Content-type: text/plain; charset=utf-8\n\nAn error has occurred"
    print
    traceback.print_exc(file = sys.stdout)
    print
    for k in sorted(form.keys()): print k,"=",form.getvalue(k)
